# Generated by Django 4.0.4 on 2022-05-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('bobina', models.CharField(max_length=9)),
                ('instrumento', models.CharField(max_length=10)),
            ],
        ),
    ]
